### ISSUE TITLE
[question] the CSS node name of  contorl box, next button, play-pause button, previous button

### ISSUE THREAD

**Issue by knm100** [jovanlanik/gtklock-playerctl-module#10]
I would like to style the contorl box, next button, play-pause button, previous button by CSS.    I have tried the following css node name, but they all can't change anything.
#contorl_box, #contorl-box,  #next-button, #next_button, #play-pause-button,#play-pause_button, #previous_button, #previous-button
could you help me to list their css node name?
![swappy-20241112-111316](https://github.com/user-attachments/assets/311fd310-3258-4a39-a414-ee70bace2a16)

**Comment by jovanlanik** [comment]
The names are `#previous-button`, `#play-pause-button` and `#next-button`. You can set the background and icon color like this:
```css
#next-button {
	background-image: none;
	background-color: red;
	color: blue;
}
```
